set pastetoggle=<F3>    #关闭黏贴板自动缩进
set nocompatible " 关闭 vi 兼容模式 
set backspace=indent,eol,start
syntax on " 自动语法高亮
"set tabstop=4 " 设定 tab 长度为 4
set ruler " 打开状态栏标尺
"set cursorline " 突出显示当前行
set hlsearch " 搜索时高亮显示被找到的文本
set showcmd " 输入的命令显示出来，看的清楚些
"set number " 显示行号
set incsearch " 输入搜索内容时就显示搜索结果
"设置字体
set fencs=utf-8,ucs-bom,shift-jis,gb18030,gbk,gb2312,cp936
set termencoding=utf-8
set encoding=utf-8
set fileencodings=ucs-bom,utf-8,cp936
set fileencoding=utf-8
set completeopt=preview,menu 
set foldenable " 开始折叠
set foldmethod=syntax " 设置语法折叠
set foldcolumn=0 " 设置折叠区域的宽度
setlocal foldlevel=1 " 设置折叠层数为
nnoremap <space> @=((foldclosed(line('.')) < 0) ? 'zc' : 'zo')<CR>
" 用空格键来开关折叠
" 自动缩进
set autoindent
set smartindent " 开启新行时使用智能自动缩进
set cindent
" 统一缩进为4
set softtabstop=4
set shiftwidth=4
"语言设置
set langmenu=zh_CN.UTF-8
set helplang=cn